### ISSUE TITLE
Tests not being done on Jenkins

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#175]
We're having trouble with our automatic testing at the moment, as pushes to the remote repository are not automatically triggering the test suite to be run on Jenkins.

Github is then left awaiting the results of tests for each of these branches.

We've also tried manually telling Jenkins to run the tests for a given branch, which seems to bring up something like the following error:
```
Started by user jshipton

java.lang.IllegalStateException: closed
	at okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:56)
	at com.squareup.okhttp.internal.DiskLruCache.get(DiskLruCache.java:433)
	at com.squareup.okhttp.Cache.get(Cache.java:184)
	at com.squareup.okhttp.Cache$1.get(Cache.java:139)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:207)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:450)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:399)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:155)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:199)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderField(DelegatingHttpsURLConnection.java:190)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:25)
	at org.kohsuke.github.Requester.noteRateLimit(Requester.java:335)
	at org.kohsuke.github.Requester._to(Requester.java:285)
	at org.kohsuke.github.Requester.to(Requester.java:224)
	at org.kohsuke.github.GitHub.checkApiUrlValidity(GitHub.java:668)
	at org.jenkinsci.plugins.github_branch_source.Connector.checkApiUrlValidity(Connector.java:324)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.checkApiUrlValidity(GitHubSCMSource.java:1380)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:1433)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:583)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:95)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:290)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

Finished: FAILURE
```

**Comment by tmbgreaves** [comment]
This should now be fixed. It seems to be a growing problem with Jenkins that the github integration is problematic, starting a few weeks back and increasing in consequences. This particular one is a problem with personal access tokens working fine for 'a few days' then failing to authenticate to github and needing updating to a different token. Wierdly, sometimes switching back to the original token works when the new one fails, which makes me wonder whether this is an issue with cache corruption in Jenkins. I've not had the chance to do any debugging, and to be honest I'm far from a Java guru so am not too optimistic of my ability to either produce a reliably failing example back to the developers or debug this effectively :-( I've not found any pattern to the failures yet, even.

I'll add in 'check access token validity' on my morning checks with Jenkins to try and catch this one early in future, but if I miss it please do ping me on slack or here and I'll fix it.

**Comment by tmbgreaves** [comment]
Thanks @jshipton for the heads-up on this one :-)
