### ISSUE TITLE
Fix replace for replacing from larger spaces again...

### ISSUE THREAD

**Issue by JHopeCollins** [firedrakeproject/gusto#389]
I would like to use the `Equation` classes to provide the forms to use in asQ. To do this I need to be able to replace the subject and test functions from the `Equation.residual` with `Function` / `TestFunction` from a different finite element space. This different space will have at least as many components as the `Equation.function_space` and will contain every component of the `Equation.function_space` but possibly not in the same order/contiguous.
Example for the shallow water equations:

```
import firedrake as fd
import gusto

from gusto.labels import replace_subject, replace_test_function, replace_trial_function, time_derivative
from gusto.fml.form_manipulation_labelling import all_terms, drop

# set up the equation
mesh = fd.UnitIcosahedralSphereMesh(refinement_level=1, degree=1)
swe_params = gusto.ShallowWaterParameters(H=1, g=1, Omega=1)
domain = gusto.Domain(mesh, dt=1, family='BDM', degree=1)
eqn = gusto.ShallowWaterEquations(domain, swe_params)

residual = eqn.residual

# function to replace the test function and subject of the time-derivative with different test function and subject.
def form_mass(u, h, v, q):
    M = residual.label_map(lambda t: t.has_label(time_derivative),
                           map_if_false=drop)

    M = M.label_map(all_terms, replace_test_function(v, idx=0))
    M = M.label_map(all_terms, replace_test_function(q, idx=1))

    M = M.label_map(all_terms, replace_subject(u, idx=0))
    M = M.label_map(all_terms, replace_subject(h, idx=1))
    return M.form

V = eqn.function_space
Vu = V.subfunctions[0]
Vh = V.subfunctions[1]

# the usual FunctionSpace

u, h = fd.TrialFunctions(V)
v, q = fd.TestFunctions(V)

M = form_mass(u, h, v, q)  # this works

# A FunctionSpace for multiple timesteps

W = V*V
u0, h0, u_, h_ = fd.split(fd.Function(W))
v0, q0, v_, q_ = fd.TestFunctions(W)

M0 = form_mass(u0, h0, v0, q0)  # this works

# A FunctionSpace to proxy the complex problem (real u, imag u, real h, imag h)

W = fd.MixedFunctionSpace((Vu, Vu, Vh, Vh))
u1, u_, h1, h_ = fd.split(fd.Function(W))
v1, v_, q1, q_ = fd.TestFunctions(W)

M1 = form_mass(u1, h1, v1, q1)  # this breaks when replacing q (the second replace_test_function call)
```

This fails with the following error on the last `form_mass` call:
```
Traceback (most recent call last):
  File "/home/jhc/codes/firedrake/src/gusto/gusto/labels.py", line 94, in repl
    new_form = ufl.replace(t.form, replace_dict)
  File "/home/jhc/codes/firedrake/src/ufl/ufl/algorithms/replace.py", line 60, in replace
    return map_integrand_dags(Replacer(mapping2), e)
  File "/home/jhc/codes/firedrake/src/ufl/ufl/algorithms/replace.py", line 24, in __init__
    raise ValueError("Replacement expressions must have the same shape as what they replace.")
ValueError: Replacement expressions must have the same shape as what they replace.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jhc/codes/asQ/examples/test_replace.py", line 52, in <module>
    M1 = form_mass(u1, h1, v1, q1)  # this breaks when replacing q (the second replace_test_function call)
  File "/home/jhc/codes/asQ/examples/test_replace.py", line 21, in form_mass
    M = M.label_map(all_terms, replace_test_function(q, idx=1))
  File "/home/jhc/codes/firedrake/src/gusto/gusto/fml/form_manipulation_labelling.py", line 286, in label_map
    functools.reduce(operator.add,
  File "/home/jhc/codes/firedrake/src/gusto/gusto/fml/form_manipulation_labelling.py", line 288, in <genexpr>
    (map_if_true(t) if term_filter(t) else
  File "/home/jhc/codes/firedrake/src/gusto/gusto/labels.py", line 98, in repl
    raise type(err)(error_message) from err
ValueError: <class 'ValueError'> raised by ufl.replace when trying to replace_test_function with v_0[6]
```

**Comment by tommbendall** [comment]
Is this fixed now? Can we close it?

**Comment by JHopeCollins** [comment]
Yes we can do this now! Here's a working equivalent with the imports updated and the correct replace incantations:

```
import firedrake as fd                                                                                                                                                                                                                                                                                                       
import gusto

from gusto import Term
from gusto.fml import replace_subject, replace_test_function, replace_trial_function
from gusto.labels import time_derivative, prognostic
from gusto.fml import all_terms, drop

from firedrake.formmanipulation import split_form

# set up the equation
mesh = fd.UnitIcosahedralSphereMesh(refinement_level=1, degree=1)
swe_params = gusto.ShallowWaterParameters(H=1, g=1, Omega=1)
domain = gusto.Domain(mesh, dt=1, family='BDM', degree=1)
eqn = gusto.ShallowWaterEquations(domain, swe_params)

residual = eqn.residual

print()
print("Original mass matrix:")
print(residual.label_map(lambda t: t.has_label(time_derivative),
                         map_if_false=drop).form)
print()

# function to replace the test function and subject of the time-derivative with different test function and subject.
def form_mass(u, h, v, q):
    M = residual.label_map(lambda t: t.has_label(time_derivative),
                           map_if_false=drop)

    # M = M.label_map(all_terms, replace_subject((u, h)))
    # M = M.label_map(all_terms, replace_test_function((v, q)))

    Mu = M.label_map(lambda t: t.get(prognostic) == "u",
                     lambda t: Term(split_form(t.form)[0].form, t.labels),
                     drop)

    Mh = M.label_map(lambda t: t.get(prognostic) == "D",
                     lambda t: Term(split_form(t.form)[1].form, t.labels),
                     drop)

    Mu = Mu.label_map(all_terms, replace_test_function(v))
    Mu = Mu.label_map(all_terms, replace_subject(u, old_idx=0))

    Mh = Mh.label_map(all_terms, replace_test_function(q))
    Mh = Mh.label_map(all_terms, replace_subject(h, old_idx=1))

    # M = Mu + Mh
    return M.form

V = eqn.function_space
Vu = V.subfunctions[0]
Vh = V.subfunctions[1]

# the usual FunctionSpace

u, h = fd.split(fd.Function(V))
v, q = fd.TestFunctions(V)

M = form_mass(u, h, v, q)
print("Simple mass matrix replacement:")
print(u, h, v, q)
print(M)
print()

# A FunctionSpace for multiple timesteps (u0, h0, u1, h1)

W0 = V*V
u0, h0, u1, h1 = fd.split(fd.Function(W0))
v0, q0, v1, q1 = fd.TestFunctions(W0)

Mt = form_mass(u1, h1, v1, q1)
print("Multiple timesteps mass matrix replacement:")
print(u1, h1, v1, q1)
print(Mt)
print()

# A FunctionSpace to proxy the complex problem (real u, imag u, real h, imag h)

W1 = fd.MixedFunctionSpace((Vu, Vu, Vh, Vh))
ur, ui, hr, hi = fd.split(fd.Function(W1))
vr, vi, qr, qi = fd.TestFunctions(W1)

Mc = form_mass(ui, hi, vi, qi)
print("Complex mass matrix replacement:")
print(ui, hi, vi, qi)
print(Mc)
print()
```

**Comment by JHopeCollins** [comment]
In fact I think we can do one better with the replacements in the `form_mass` function. The version above is modelled off @jshipton's rexi code, but if you don't have to handle the different real/imaginary components then you can simplify it to the version below (you might also be able to do this with the complex code, I haven't tried yet.

```
# function to replace the test function and subject of the time-derivative with different test function and subject.
def form_mass(u, h, v, q):
    M = residual.label_map(lambda t: t.has_label(time_derivative),
                           map_if_false=drop)

    M = M.label_map(all_terms, replace_subject((u, h)))
    M = M.label_map(all_terms, replace_test_function((v, q)))
    return M.form
```
