### ISSUE TITLE
Error when picking up from a checkpoint in parallel

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#447]
I was testing our parallel logging by trying to pick up the Williamson 2 example from a checkpoint dump and my simulation hung.

Inspection of the different log files (showing how useful they are!) showed that rank 0 was hanging, but the other ranks were throwing an error relating to the netcdf field outputting:
```
2023-09-20 08:10:23,829 ERROR    Gusto is logging this unhandled exception:
Traceback (most recent call last):
  File "/home/thomas/firedrake/src/gusto/examples/shallow_water/williamson_2.py", line 108, in <module>
    stepper.run(t=0, tmax=tmax, pick_up=pick_up)
  File "/home/thomas/firedrake/src/gusto/gusto/timeloop.py", line 618, in run
    super().run(t, tmax, pick_up=pick_up)
  File "/home/thomas/firedrake/src/gusto/gusto/timeloop.py", line 191, in run
    self.io.dump(self.fields, float(self.t), self.get_initial_timesteps())
  File "/home/thomas/firedrake/src/gusto/gusto/io.py", line 662, in dump
    self.write_nc_dump(t)
  File "/home/thomas/firedrake/src/gusto/gusto/io.py", line 780, in write_nc_dump
    self.field_t_idx += 1
AttributeError: 'IO' object has no attribute 'field_t_idx'
```

**Comment by tommbendall** [comment]
Closing as fixed by #448
